### ISSUE TITLE
RemoveMagicLib Bugs

### ISSUE THREAD

**Issue by jcefoli** [mRemoteNG/mRemoteNG#1248]
To keep GitHub issue tracker clean, here is a list of issues I found in the RemoveMagicLib branch as of 3b35e5a44d93748b6d39f24ea02ec5d7c01b7528:

- [x] After initial RDP connection with SmartSize, resizing the main window  does not resize the RDP frame
- [x] After initial RDP connection with Fit to Panel, resizing the main window does not cause RDP session to reconnect with new frame's resolution
- [x] RDP tabs only disconnect properly when you right click --> disconnect in the connection list. When the tab is X ed out or middle clicked, it vanishes correctly, but the server in the connection list still has the play button icon. double clicking the server to reconnect does not work. The workaround is to right click the server in the connection list and reconnect
  * - [x] "Disconnect all but this" option also has the above issue
  * - [x] "Disconnect all tabs to the right" option also has the above issue
- [x] ~External Tools tab right click/tabbar rightclick option doesn't seem to do anything... When you go to View --> External Tools, the pane layout is hidden and it gets added in a weird way to the bottom notification pane. Reset layout does not fix this.~
- [x] Right click tab/tabbar --> Screenshot is not working. It loads the screenshot pane, but no image is snapped and doesn't save if you attempt to (even though the file picker dialog appears). Works in develop
- [x] Double click to close doesn't work
- [x] Review reconnect all logic: mMenReconnectAll_Click
- [x] Review references to ConnectionWindow to see if they need to be replaced with ConnectionTab accordingly
- [x] Remove or refactor/rename remaining TabController references (many of which are commented out)
- [x] Icons do not display on the connection tabs. Reference AddConnectionTab in ConnectionWindow.cs

(Normally, I'd be more detailed with actual/expected behavior and more info, but this is just a catch-all ticket for anything obvious in an experimental feature branch. I'll be in Gitter if you need clarification on anything)

**Comment by kmscode** [comment]
Resizing works. Fixed in c07e2e48d02813e960b131394dd11c7ac66bd7a2

**Comment by kmscode** [comment]
@jcefoli I think the RDP disconnect might also be fixed in the above commit. At least, I can't reproduce it after that commit, but didn't test before it. Please let me know...

**Comment by kmscode** [comment]
@jcefoli could you please clarify the external tools problem and/or provide a screen shot. In my testing (even in previous versions) external tools pane was added to the bottom and could then be relocated as desired. In the current branch it is visible and movable.

The magiclib removal should have impacted this since it's in a ToolStripContainer that gets added directly to the main panel - DPS and MagicLib aren't involved at that level...

**Comment by jcefoli** [comment]
Verified that smartsize and fit to tab work correctly. Ignore my External Tools issue - I see it's working fine now.

Regarding the last item on the list which is unchecked (the tab disconnect), it's partially fixed. When I disconnect, I can now double click the server in the connection pane and it will reconnect again. However, when disconnected, the connection panel still shows the play button even if the tab's been closed. I'm not sure if it's just a GUI issue or if it's still actively connected but not visible:

![image](https://user-images.githubusercontent.com/6618013/50675078-c5002c00-0fb9-11e9-8915-068b7fae6f3e.png)

I also noticed that right click on a tab/tabbar and screenshot does not work. It seems to work in the develop branch

**Comment by kmscode** [comment]
@jcefoli I can't seem to reproduce the play icon issue. But the title bar isn't updating after the disconnect. That I've reproduced. Maybe after reviewing/fixing the title bar thing, the play icon overylay will be fixed for you (or I find a smoking gun in the code).

I've also added a few more items to the list after reviewing the code and some of the other fixes that have already been implemented. 

Thanks again for your testing and attention to detail on this branch!

**Comment by kmscode** [comment]
screenshots implemented in edfbad2432b5dc20ac980187caa105a8c3ecec62

**Comment by kmscode** [comment]
For the titlebar problem, FrmMain.Default.SelectedConnection = (ConnectionInfo) will need to be called from somewhere (haven't figured out where yet) so UpdateWindowTitle() is called accordingly.

**Comment by jotatsu** [comment]
All the tab controller references should be removed now, comments included

**Comment by kmscode** [comment]
We now have icons! 4ac51a7e582d1d4e437b6548b89a02e18716ce6d

**Comment by kmscode** [comment]
double click to close implemented by @jotatsu as of 7603587ce3f55cbf13aa7043100a5445d031b6e4

**Comment by kmscode** [comment]
Marking this one as done. Pretty sure we got to everything on the list. Please open new issues accordingly if you encounter any problems.
